# 9.错误处理

前八章集中于特定的用例:安装、执行查询、处理结果等。在一些地方，提到了错误处理的重要性，但是没有提供太多的细节。这种情况即将改变，因为这一章专门讨论错误处理。

错误处理是所有编程中最重要的主题之一，不仅仅是在使用 MySQL Connector/Python 时。你可以说它和测试应该是你学习的两个首要主题。这种说法有很大程度的真实性；然而，我决定将错误处理放在本书的倒数第二章。不是因为它不重要(短语“最后但并非最不重要”当然适用于本章和下一章关于故障排除的内容)，而是因为两个原因:首先，这不是一本像使用 MySQL Connector/Python 那样关于编程的书，所以假设您已经很好地掌握了编程最佳实践。第二，它允许我给例子更多的上下文。

### 注意

不要将错误处理和测试视为次要任务。确保它们的优先级至少和实现实际功能的优先级一样高。这并不是 MySQL Connector/Python 独有的。

本章将从 MySQL 服务器中的警告、错误和*严格模式*开始。然后，您将继续讨论 MySQL Connector/Python 本身，在这里，讨论的第一部分将是一般的警告和错误处理、警告配置以及如何获取警告。第二部分将讨论 MySQL 错误号和 SQL 状态。最后，第三部分将概述`mysql.connector`和`mysqlx`模块的错误类别。

### 小费

本章中有许多示例程序。列表中出现的所有示例程序都可以下载。有关使用示例程序的更多信息，参见第 [1](01.html) 章中对示例程序的讨论。

## MySQL 服务器中的警告、错误和严格模式

在讨论 MySQL Connector/Python 中的错误处理时，在连接的 MySQL 服务器端需要考虑一些事情。本节将查看配置设置，以指定注释级消息是否应被视为警告，严格模式如何工作，以及应用程序如何将消息记录在 MySQL 错误日志中。

### 将注释级别的消息视为警告

执行语句时发生的事件有三个严重级别。最严重的是一个总是阻止语句完成的错误。下一个级别是警告，允许语句完成，但向用户或应用程序返回警告，以便决定要做什么。严重性最低的是音符级别，这是本次讨论的主题。

默认情况下，语句的注释级消息(例如，如果数据库存在，并且您试图使用`CREATE DATABLASE IF NOT EXISTS`创建它)会导致出现警告。例如:

```py
mysql> CREATE SCHEMA IF NOT EXISTS py_test_db;
Query OK, 1 row affected, 1 warning (0.28 sec)

mysql> SHOW WARNINGS\G
*************************** 1\. row ***************************
  Level: Note
   Code: 1007
Message: Can't create database 'py_test_db'; database exists
1 row in set (0.00 sec)

```

请注意，在`SHOW WARNINGS`输出中，电平为`Note`。可以避免产生警告的注释级消息。这是通过改变`sql_notes`选项的值来实现的。当`sql_notes`的值为`ON`(默认值)时，会产生一个警告。如果是`OFF`，则不产生警告。该选项可以针对会话进行更改，因此，如果您通常希望发出警告，但对于给定的语句，您希望禁用它，则可以禁止显示该消息。要暂时隐藏注释级别的消息，您可以使用以下工作流程:

```py
mysql> SET SESSION sql_notes = OFF;
Query OK, 0 rows affected (0.00 sec)

-- Execute statements

mysql> SET SESSION sql_notes = ON;
Query OK, 0 rows affected (0.00 sec)

```

因此，如果您知道一个查询将导致一个注释级消息，那么您可以在执行该语句时更改会话的值`sql_notes`。然而，一般来说，最好是通过改变陈述来避免该消息。

### 小费

建议启用`sql_notes`,仅对您知道不需要警告的特定语句禁用它。

### 严格模式

服务器端配置的第二部分是严格模式。当启用严格模式时，它会告诉 MySQL 将无效数据视为错误而不是警告。在 MySQL 的旧版本中，默认情况下会容忍不适合表的数据，并尽最大努力使其适合。这使得开发应用程序变得更加容易，但是这样做的一个主要缺点是，它可能会导致数据库以与预期不同的数据结束。

强制数据适应的操作示例有将字符串转换为整数或截断数据。考虑名为`table_1`的表，其定义如下:

```py
mysql> CREATE SCHEMA db1;
Query OK, 1 row affected (0.41 sec)

mysql> CREATE TABLE db1.table_1 (
          id int unsigned NOT NULL PRIMARY KEY,
          val varchar(5)
       ) ENGINE=InnoDB;
Query OK, 0 rows affected (0.24 sec)

```

在未启用严格模式的情况下，尝试插入六个字符的值将会导致警告，但仍会插入值被截断为五个字符的行:

```py
mysql> INSERT INTO db1.table_1 VALUES (1, 'abcdef');
Query OK, 1 row affected, 1 warning (0.15 sec)

mysql> SHOW WARNINGS\G
*************************** 1\. row ***************************
  Level: Warning
   Code: 1265
Message: Data truncated for column 'val' at row 1
1 row in set (0.00 sec)

mysql> SELECT * FROM table_1;
+----+-------+
| id | val   |
+----+-------+
|  1 | abcde |
+----+-------+
1 row in set (0.00 sec)

```

在 MySQL 5.7 和更高版本中，默认情况下为事务表启用严格模式(`InnoDB`和`NDBCluster`存储引擎)。在这种情况下，如果数据不合适，就会出现错误。防止插入的严格模式的一个例子是

```py
mysql> INSERT INTO db1.table_1 VALUES (2, 'ghijkl');
ERROR 1406 (22001): Data too long for column 'val' at row 1

```

事务表的严格模式是通过在 SQL 模式列表中包含`STRICT_TRANS_TABLES`来实现的。有关 SQL 模式的更多信息，请参见 [`https://dev.mysql.com/doc/refman/en/sql-mode.html`](https://dev.mysql.com/doc/refman/en/sql-mode.html) 。从 MySQL 连接器/Python 内部，可以使用`sql_mode`连接选项设置 SQL 模式。

与`STRICT_TRANS_TABLES` SQL 模式相关的是`innodb_strict_mode`选项。此选项仅适用于 InnoDB 表格。SQL 模式控制数据修改语言(DML)查询，而`innodb_strict_mode`选项控制数据定义语言(DDL)查询，如`CREATE TABLE`、`ALTER TABLE`和`CREATE INDEX`。由`innodb_strict_mode`选项触发错误的一个最常见的原因是，当创建一个表时，其定义将导致该表的最大可能行大小超过 InnoDB 的限制。

强烈建议同时启用`STRICT_TRANS_TABLES` SQL 模式和`innodb_strict_mode`选项。在开始开发应用程序之前启用它，这样您就可以尽早得到关于不兼容问题的警告。

### 小费

与完成应用程序之后相比，在初始开发阶段修复违反严格模式的情况要容易得多。因此，在开始编码之前，启用严格模式；从长远来看，这会节省你的工作。

### MySQL 错误日志

在 MySQL 服务器端需要注意的最后一点是，应用程序执行(或不执行)的操作可能会触发 MySQL 错误日志中的消息。例如，如果应用程序试图使用无效凭据进行连接，或者它没有正确关闭其连接，则可能会出现类似于以下示例的消息:

```py
2018-03-03T04:10:19.943401Z 52 [Note] [MY-010926] Access denied for user 'pyuser'@'localhost' (using password: YES)

2018-03-03T04:10:28.330173Z 53 [Note] [MY-010914] Aborted connection 53 to db: 'unconnected' user: 'pyuser' host: 'localhost' (Got an error reading communication packets).

```

第一条消息说来自`localhost`的`pyuser`用户试图使用密码进行连接，但是密码是错误的(或者该用户不存在)。第二条消息指出，在试图从其中一个连接中读取数据时出现了错误。在这种情况下，是因为连接消失了。

这些消息只有在`log_error_verbosity` MySQL 服务器选项设置为 3 时才会显示。建议在开发过程中确保这一点，并定期检查错误日志以捕获应用程序触发的所有消息。这可以通过在 MySQL 配置文件中设置选项来实现。在 MySQL 8.0 中，也可以使用如下的`SET PERSIST`语句来实现:

```py
mysql> SET PERSIST log_error_verbosity = 3;
Query OK, 0 rows affected (0.04 sec)

```

这段代码设置当前值，并在 MySQL 重启时保存该值。

关于 MySQL 服务器已经说得够多了。下一个主题是 MySQL 连接器/Python 本身的警告和错误处理。

## 警告和错误处理

当您在程序中使用 MySQL Connector/Python 时，您会遇到内置 Python 异常和您使用的 MySQL Connector/Python 模块的自定义异常的混合。此外，还有一个子模块将 MySQL 错误代码作为常量。本节将介绍与警告相关的配置以及如何获取警告。MySQL 错误号、SQL 状态和异常类将在接下来的两节中讨论。

### 配置

当您使用`mysql.connector`模块中的方法时，可以配置 MySQL 连接器/Python 应该如何处理警告。有两个选项:是否自动获取查询的所有警告，以及是否将警告提升为异常。

MySQL 处理三种不同严重级别的错误消息:

*   **注意**:这只是一个关于所发生事情的通知。这通常不是问题的征兆。例如，当您使用`CREATE DATABASE IF NOT EXISTS`创建一个数据库(模式)并且该数据库确实存在时，就会出现一个注释。在某些情况下，如果注意到了，通常这可能是潜在问题或不良做法的迹象。因此，您不应该自动忽略音符级别的信息。默认情况下，注释级消息被视为警告；这由`sql_notes` MySQL 服务器选项控制。

*   **警告**:这是不妨碍 MySQL 继续下去的事情，但是行为可能不是你所期待的。例如，如果您提供的值不符合列定义，MySQL 会截断或转换所提供的值，就会发生这种情况。如果 MySQL 服务器启用了严格模式，一些警告(如示例中的警告)可能会升级为错误。

*   **错误**:这是针对阻止 MySQL 执行查询的情况。他们总是会在 MySQL Connector/Python 中抛出一个异常。一个例子是出现了重复键错误。

一般来说，建议认真对待所有警告和错误。警告通常是事情不正常的迹象，在发展的第一阶段处理警告可以避免以后的重大灾难。

### 小费

如果您从应用程序开发的一开始就处理所有警告，您就不会被意外的数据转换或其他问题所困扰。如果警告被忽视，那么一个字符的输入错误在被发现之前可能会导致多年的问题。

当使用`mysql.connector`模块连接到 MySQL 时，有两个选项控制 MySQL 连接器/Python 如何处理警告。它们在表 [9-1](#Tab1) 中列出。

表 9-1

警告相关选项

<colgroup><col class="tcol1 align-left"> <col class="tcol2 align-left"> <col class="tcol3 align-left"></colgroup> 
| 

名字

 | 

缺省值

 | 

描述

 |
| --- | --- | --- |
| `get_warnings` | `False` | 当设置为`True`时，每次查询后自动提取警告。这使得无需手动执行`SHOW WARNINGS`即可获取警告。 |
| `raise_on_warnings` | `False` | 当设置为`True`时，警告会引发异常。设置`raise_on_warnings`总是将`get_warnings`设置为相同的值。**注意:**在获取警告之前，不会引发异常。对于有结果的查询，这意味着何时提取行。 |

这两个选项仅在使用游标时适用。在撰写本文时，没有选项可以改变在`mysqlx`模块中使用 X DevAPI 时的警告行为。

也可以在连接完成后改变`get_warnings`和`raise_on_warnings`的值。例如，这对于临时启用或禁用设置非常有用，如以下代码片段所示:

```py
import mysql.connector

db = mysql.connector.connect(
  get_warnings=True,
  raise_on_warnings=True,
  option_files="my.ini",
)

cursor = db.cursor()

db.get_warnings = False

db.raise_on_warnings = False

cursor.execute(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")

db.get_warnings = True

db.raise_on_warnings = True

db.close()

```

建议至少在开发期间启用`raise_on_warnings`和`get_warnings`。在生产中，也建议至少检查警告。与手动获取警告相比，`get_warnings`选项没有任何开销，因为只有当查询返回警告时才会执行`SHOW WARNINGS`语句。当`get_warnings`启用时，可以使用`fetchwarnings()`方法检索警告。谈到`fetchwarnings()`，我们来看看警告是如何获取的。

### 在 cmd_query()之后提取警告

在`mysql.connector`模块中，获取警告的方式取决于是通过连接对象还是游标执行查询。在这两种情况下，都使用`SHOW WARNINGS`语句来检索警告，但是游标允许您让它为您处理这个问题。

当您直接通过连接对象执行查询时，您必须自己获取警告。此外，您必须注意在获取警告之前获取所有的行，因为否则您将得到一个错误，即您有未读的行。如果您启用了`consume_results`,则应格外小心，因为在这种情况下获取警告将导致原始结果被取消。

### 警告

如果您已经启用了`consume_results`，那么执行`SHOW WARNINGS`来获得查询的警告将会消除任何未完成的行。

根据使用 C 扩展还是纯 Python 实现，在使用`cmd_query()`时处理警告的方式有所不同。因此，这两种情况都值得一看。

清单 [9-1](#Par50) 展示了一个使用 C 扩展实现的例子，警告是在一个`CREATE TABLE`语句和一个`SELECT`语句之后获取的。

```py
import mysql.connector

def print_warnings(warnings):

  if mysql.connector.__version_info__[0:3] > (8, 0, 11):
    (warnings, eof) = warnings

  for warning in warnings:
    print("Level  : {0}".format(
      warning[0]))
    print("Errno  : {0}".format(
      warning[1]))
    print("Message: {0}".format(
      warning[2]))

db = mysql.connector.connect(
  option_files="my.ini", use_pure=False)

# This example only works with the C
# Extension installed. Exit if that is
# not the case.
is_cext = isinstance(
  db,
  mysql.connector.connection_cext.CMySQLConnection
)
if not is_cext:
  print("The example requires the C "
    + "Extension implementation to be "
    + "installed")
  exit()

print("Using the C Extension implementation\n")

# Ensure the DDL statement will cause
# a warnings by executing the same
# CREATE SCHEMA IF NOT EXISTS statement
# twice.
db.cmd_query(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")

# For a DDL statement
result = db.cmd_query(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")

print("Warnings for CREATE SCHEMA:")
print("---------------------------")

print("DDL: Number of warnings: {0}"

  .format(result["warning_count"]))

# Get the warnings

db.cmd_query("SHOW WARNINGS")

warnings = db.get_rows()

print_warnings(warnings)
db.free_result()
print("")

# Try a SELECT statement
result = db.cmd_query("SELECT 1/0")
rows = db.get_rows()
db.free_result()

print("Warnings for SELECT:")
print("--------------------")

print("SELECT: Number of warnings: {0}"

  .format(db.warning_count))

# Get the warnings
db.cmd_query("SHOW WARNINGS")
warnings = db.get_rows()
print_warnings(warnings)

db.close()

Listing 9-1Checking Warnings with the C Extension Implementation and cmd_query()

```

警告打印在`print_warnings()`功能中。在 8.0.12 版和更高版本中使用 C 扩展时，由于有一个变化，所以`eof`包也包括在内，因此有必要拥有版本相关的代码。`__version_info__`房产用于此。

对于`CREATE TABLE`语句，`cmd_query()`返回的结果直接将警告数作为`warning_count`元素。对于`SELECT`的说法，稍微复杂一点。首先需要使用结果，然后可以在连接对象的`warning_count`属性中找到警告的数量。

警告本身是使用`SHOW WARNINGS`语句获取的，这些语句像任何其他语句一样执行。输出是

```py
Using the C Extension implementation

Warnings for CREATE SCHEMA:
---------------------------
DDL: Number of warnings: 1
Level  : Note
Errno  : 1007
Message: Can't create database 'py_test_db'; database exists

Warnings for SELECT:
--------------------
SELECT: Number of warnings: 1
Level  : Warning
Errno  : 1365
Message: Division by 0

```

每个 warning()有三个元素:严重性(注意、警告或错误)、错误号(将在本章后面讨论)和描述错误的错误消息。如果 C 扩展名不可用，程序将退出并显示错误:

```py
The example requires the C Extension implementation to be installed

```

如果使用纯 Python 实现，会有一些不同。首先，`SELECT`语句的警告计数可以在所有版本的`get_row()`或`get_rows()`返回的`eof`部分中找到。另一件事是`SHOW WARNINGS`语句()的结果在 MySQL Connector/Python 8.0.11 中是以字节数组的形式返回的，所以必须解码。清单 [9-2](#Par57) 展示了 8.0.12 及更高版本的示例的纯 Python 等价物。代码示例包括文件 Chapter _ 09/listing _ 9 _ 2 _ version _ 8 _ 0 _ 11 . py 中的 8.0.11 和更早版本。

```py
import mysql.connector

def print_warnings(warnings):
  for warning in warnings:
    print("Level  : {0}".format(
      warning[0]))
    print("Errno  : {0}".format(
      warning[1]))
    print("Message: {0}".format(
      warning[2]))

db = mysql.connector.connect(
  option_files="my.ini", use_pure=True)

print("Using the pure Python implementation\n")

# Ensure the DDL statement will cause
# a warnings by executing the same
# CREATE SCHEMA IF NOT EXISTS statement
# twice.
db.cmd_query(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")

# For a DDL statement
result = db.cmd_query(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")

print("Warnings for CREATE SCHEMA:")
print("---------------------------")
print("DDL: Number of warnings: {0}"
  .format(result["warning_count"]))

# Get the warnings

db.cmd_query("SHOW WARNINGS")

(warnings, eof) = db.get_rows()

print_warnings(warnings)
print("")

# Try a SELECT statement
result = db.cmd_query("SELECT 1/0")
(rows, eof) = db.get_rows()

print("Warnings for SELECT:")
print("--------------------")
print("SELECT: Number of warnings: {0}"
  .format(eof["warning_count"]))

# Get the warnings

db.cmd_query("SHOW WARNINGS")

(warnings, eof) = db.get_rows()

print_warnings(warnings)

db.close()

Listing 9-2Checking Warnings with the Pure Python Implementation and cmd_query()

```

该示例经历了与前面相同的步骤，但是这一次在获取行时从`eof`部分检索到了`SELECT`语句的警告数。和以前一样，警告计数只有在获取了所有行()后才可用。除了头之外，该示例的输出与之前相同:

```py
Using the pure Python implementation

Warnings for CREATE SCHEMA:
---------------------------
DDL: Number of warnings: 1
Level  : Note
Errno  : 1007
Message: Can't create database 'py_test_db'; database exists

Warnings for SELECT:
--------------------
SELECT: Number of warnings: 1
Level  : Warning
Errno  : 1365
Message: Division by 0

```

如果使用游标，事情通常会简单一些。让我们看看光标和警告是如何工作的。

### 用游标提取警告

用光标获取警告时所做的工作原则上与使用`cmd_query()`方法获取警告时相同。然而，许多工作是由光标在后台处理的，这总体上使它更容易使用。

清单 [9-3](#Par63) 显示了清单 [9-1](#Par50) 和清单 [9-2](#Par57) 中检查的等价示例，只是这次使用了一个光标，并启用了`get_warnings`。

```py
import mysql.connector

def print_warnings(warnings):
  for warning in warnings:
    print("Level  : {0}".format(
      warning[0]))
    print("Errno  : {0}".format(
      warning[1]))
    print("Message: {0}".format(
      warning[2]))

print("Using cursors\n")

db = mysql.connector.connect(
  option_files="my.ini")

cursor = db.cursor()

# Ensure the DDL statement will cause
# a warnings by executing the same
# CREATE SCHEMA IF NOT EXISTS statement
# twice.
cursor.execute(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")

# Enable retriaval of warnings

db.get_warnings = True

# For a DDL statement
cursor.execute(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")

# Get the warnings

warnings = cursor.fetchwarnings()

print("Warnings for CREATE SCHEMA:")
print("---------------------------")
print("DDL: Number of warnings: {0}"
  .format(len(warnings)))
print_warnings(warnings)
print("")

# Try a SELECT statement
cursor.execute("SELECT 1/0")

rows = cursor.fetchall()

# Get the warnings
warnings = cursor.fetchwarnings()

print("Warnings for SELECT:")
print("--------------------")
print("SELECT: Number of warnings: {0}"
  .format(len(warnings)))
print_warnings(warnings)

db.close()

Listing 9-3Fetching Warnings Using a Cursor with get_warnings Enabled

```

在执行任何查询之前，`get_warnings`选项被启用。这也可以在选项文件中完成，或者作为`mysql.connector.connect()`函数的一个单独的参数。

启用`get_warnings`后，DDL 和`SELECT`语句获得警告的工作流是相同的。这是这种方法的主要优点。使用光标的`fetchwarnings()`方法获取警告。这将以与上一示例相同的方式返回警告列表。发现警告的数量是列表的长度。对于`SELECT`语句，您必须在获取警告之前检索结果集中的所有行。输出与清单 [9-1](#Par50) 和清单 [9-2](#Par57) 相同:

```py
Using cursors

Warnings for CREATE SCHEMA:
---------------------------
DDL: Number of warnings: 1
Level  : Note
Errno  : 1007
Message: Can't create database 'py_test_db'; database exists

Warnings for SELECT:
--------------------
SELECT: Number of warnings: 1
Level  : Warning
Errno  : 1365
Message: Division by 0

```

### 用 X DevAPI 获取警告

使用 X DevAPI 时对警告的处理类似于它对游标的工作方式。最大的区别是警告是结果对象的一部分。这确保了不管使用 X DevAPI 的哪一部分和执行的查询类型如何，都有一个统一的处理警告的方法。

无论返回哪种结果对象，警告的处理都使用相同的两种方法。这两种方法是

*   `get_warnings()`:返回查询生成的警告元组列表

*   `get_warnings_count()`:返回一个带有警告数的整数

不需要在查询前启用警告。警告总是可用的。

作为一个例子，让我们重复一下用于`cmd_query()`和光标的例子，看看在使用 X DevAPI 的程序中如何处理警告。结果代码可以在清单 [9-4](#Par73) 中看到。

```py
import mysqlx
from config import connect_args

db = mysqlx.get_session(**connect_args)

# Ensure the DDL statement will cause
# a warnings by executing the same
# CREATE SCHEMA IF NOT EXISTS statement
# twice.
sql = db.sql(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")
sql.execute()

# For a DDL statement
sql = db.sql(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")
result = sql.execute()

# Get the warnings
print("Warnings for CREATE SCHEMA:")
print("---------------------------")
print("DDL: Number of warnings: {0}"
  .format(result.get_warnings_count()))

print(result.get_warnings())

print("")

# Try a SELECT statement
sql = db.sql("SELECT 1/0")
result = sql.execute()

row = result.fetch_all()

# Get the warnings
print("Warnings for SELECT:")
print("--------------------")
print("SELECT: Number of warnings: {0}"
  .format(result.get_warnings_count()))
print(result.get_warnings())

db.close()

Listing 9-4Handling Warnings with the X DevAPI

```

该示例类似于游标示例，只是可以使用`get_warnings_count()`方法而不是使用警告列表的长度来找到警告计数。对于作为结果的一部分返回行或文档的查询，在检索警告之前必须获取结果。输出是

```py
Warnings for CREATE SCHEMA:
---------------------------
DDL: Number of warnings: 1
[{'level': 1, 'code': 1007, 'msg': "Can't create database 'py_test_db'; database exists"}]

Warnings for SELECT:
--------------------
SELECT: Number of warnings: 1
[{'level': 2, 'code': 1365, 'msg': 'Division by 0'}]

```

输出显示警告作为字典列表返回。与其他示例相比，输出中有一个主要区别:严重性级别是一个整数，而不是一个字符串。可以返回的级别是 1 和 2，其含义如下:

*   **1** :这是一个音符级别的信息。

*   **2** :这是一个警告级别的消息。

警告字典的代码元素是 MySQL 错误号，但是 1007 是什么意思呢？我们来看看。

## MySQL 错误号和 SQL 状态

MySQL 使用错误号来指定发生了哪个注释、警告或错误事件。您在示例中看到了警告是如何包含错误号的。对于下一节讨论的异常，错误号也起着重要作用。所以在继续之前，让我们暂停一下，更详细地考虑一下错误号。

错误号是四到五位数，用于唯一标识遇到的警告或错误。这些数字是 MySQL 特有的，因此不能与其他数据库系统中的错误进行比较。如果错误号不再相关，可以不再使用，但不会重复使用。这意味着检查是否遇到了给定的错误号并据此采取行动是安全的。

除了错误号，还有 SQL 状态，这意味着可以跨 SQL 数据库移植。这种可移植性的代价是无法对错误进行详细说明。然而，SQL 状态很适合用来表示一组错误。SQL 状态仅作为错误异常的一部分返回。

本节的其余部分将查看错误号和 SQL 状态。

### MySQL 错误号

每个已知错误的错误号和 SQL 状态可以在 [`https://dev.mysql.com/doc/refman/en/error-handling.html`](https://dev.mysql.com/doc/refman/en/error-handling.html) 中找到。这些错误分为服务器端错误和客户端错误。客户端错误的数字都在 2000 到 2999 之间。服务器端错误使用范围 1000-1999 和 3000 以上。正如这些范围所表明的，有成千上万的错误号，并且这个数字随着每个 MySQL 版本的增加而增加。

幸运的是，MySQL Connector/Python 有一个映射到常量的错误号列表。如果您需要检查是否遇到了给定的错误，这允许您使用应用程序中的常量。当您在编写代码几年后再阅读代码时，使用常量可以更容易地发现错误所在。

对于`mysql.connector`和`mysqlx`模块，错误代码常量在`errorcode`子模块中定义，用法相同。清单 [9-5](#Par87) 显示了一个检查当试图创建一个数据库时返回的警告是否是该数据库已经存在的例子；在这种情况下，忽略该警告是安全的，因为您已经知道该数据库可能存在。

```py
import mysqlx

from mysqlx.errorcode import *

from config import connect_args

db = mysqlx.get_session(**connect_args)

# Ensure the DDL statement will cause
# a warnings by executing the same
# CREATE SCHEMA IF NOT EXISTS statement
# twice.
sql = db.sql(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")
sql.execute()

# For a DDL statement
sql = db.sql(
  "CREATE SCHEMA IF NOT EXISTS py_test_db")
result = sql.execute()

# Get the warnings
for warning in result.get_warnings():
  if warning["code"] == ER_DB_CREATE_EXISTS:
    print("Ignoring the warning")
  else:
    raise mysqlx.errors.DatabaseError(
      warning["msg"], warning["code"])

db.close()

Listing 9-5Comparing an Error Code Against a Constant from the errorcode Module

```

这个例子从`mysqlx.errorcode`模块导入所有的错误代码。这允许您检查警告的错误号是否为`ER_DB_CREATE_EXISTS` (1007)。如果是，警告将被忽略；否则，该警告将用于引发异常。

MySQL 连接器/Python 错误异常还包括 SQL 状态，所以在讨论异常类之前，让我们先来看看 SQL 状态。

### SQL 状态

与 MySQL 错误号不同，SQL 状态在所有 SQL 数据库之间共享。如果您编写的代码支持不同的底层数据库存储，那么最好尽可能多地使用 SQL 状态，因为这样更有可能保持应用程序的可移植性。SQL 状态也可以用来确定错误的类别。在 MySQL Connector/Python 中，SQL 状态仅用于错误异常。

SQL 状态由五个字母和数字组成。前两个字符定义类别，其余三个字符提供详细信息。在表 [9-2](#Tab2) 中可以看到一些常见的错误类别。`Exception`列是用于该 SQL 状态类的异常类。

表 9-2

常见 SQL 状态类

<colgroup><col class="tcol1 align-left"> <col class="tcol2 align-left"> <col class="tcol3 align-left"> <col class="tcol4 align-left"></colgroup> 
| 

班级

 | 

描述

 | 

例外

 | 

评论

 |
| --- | --- | --- | --- |
| 00 | 成功 |   | 查询已成功执行。这绝不会导致异常。 |
| 01 | 警告 |   | 该查询会导致警告。只有启用了`raise_on_warnings`选项，才会导致异常。 |
| 02 | 尚无数据 | `DataError` | 当查询不再有数据时，这可能源于存储的程序。 |
| 08 | 连接异常 | `OperationalError` | 这涵盖了创建连接时的各种问题，如*连接过多*，MySQL Connector/Python 不支持服务器请求的认证协议等。对于此 SQL 状态类，错误必须发生在服务器端。 |
| Twenty-one | 数错了 | `DataError` | 例如，在给定的值数目与指定的字段数目不匹配的插入中会发生这种情况。 |
| Twenty-two | 数据不符合 | `DataError` | 例如，如果字符串对于列来说太长，或者数值超出范围，就会出现这种情况。 |
| Twenty-three | 违反约束 | `IntegrityError` | 当唯一键约束失败、违反外键或试图将`NULL`指定为`NOT NULL`列的值时发生。 |
| Twenty-five | 无效的事务状态 | `ProgrammingError` | 如果您试图执行当前事务状态不允许的操作，则会发生这种情况。例如，如果您试图在只读事务中插入数据。 |
| Twenty-eight | 未授权 | `ProgrammingError` | 由于使用了错误的凭据，连接失败。 |
| 三维（three dimension 的缩写） | 没有模式 | `ProgrammingError` | 在没有默认数据库(架构)的情况下执行查询，并且查询中没有显式设置数据库时发生。 |
| Forty | 交易错误 | `InternalError` | 例如，这可能是由于死锁而发生的。另一个原因是使用 MySQL 组复制，事务在提交期间回滚，因为它不能应用于所有节点。 |
| forty-two | 语法错误或无法访问 | `ProgrammingError` | 当 SQL 语句无效或您无权访问所请求的数据时，会出现此错误。 |
| 【男子名】亨利 | 其他错误 | `DatabaseError` | 对于没有定义更具体的 SQL 状态的错误。例如，这包括 InnoDB 的锁等待超时。MySQL 错误号 1210 和 1243 是使用`DatabaseError`异常类的例外；这两个错误反而引发了一个`ProgrammingError`异常。 |
| 辅助放大器（auxiliary amplifier 的缩写） | XA 交易 | `IntegrityError` | 用于与 XA 事务相关的所有错误。 |

还有更多 SQL 状态类，但是表 [9-2](#Tab2) 中列出的是 MySQL Connector/Python 中最常见的。每个 SQL 状态类都映射到一个异常类。所以，让我们看看异常类是如何工作的。

### 警告

语法错误(SQL 状态类 42)可能是 SQL 注入尝试的迹象。确保给予这些错误高优先级。

## 异常类

MySQL Connector/Python 使用异常来报告在连接器内部处理命令时遇到的错误，或者在执行查询时出现错误。例外可以是三个类别之一，如本节所述。

可能的异常类别包括从标准 Python 异常到开发人员创建的自定义异常。这三个类别是

*   **标准 Python 异常**:用于与 MySQL 无关的错误，不再赘述。

*   **MySQL Connector/Python 内置异常**:遇到 MySQL 相关错误时会遇到的异常，除非该异常已被自定义异常覆盖。

*   自定义异常:可以定义自己的异常，并为给定的 MySQL 错误号注册它。

本节的其余部分将讨论内置的 MySQL 连接器/Python 异常和自定义异常。

### 内置类

根据错误的类型，在 MySQL Connector/Python 中预定义了许多异常类。让我们来探索它们。

无论是使用`mysql.connector`还是`mysqlx`模块，预定义的类都是相同的，我们将一起讨论它们。这些职业都使用`errors.Error`职业作为他们的基础，除了`Warning`职业。所有基于`errors.Error`的类都有相同的可用属性。

表 [9-3](#Tab3) 总结了 MySQL 连接器/Python 中使用的异常类以及它们在哪个(哪些)模块中可用。所有的类都存在于`errors`子模块中(即`mysql.connector.errors`或`mysqlx.errors`，取决于所使用的模块)。

表 9-3

MySQL 连接器/Python 异常类

<colgroup><col class="tcol1 align-left"> <col class="tcol2 align-left"> <col class="tcol3 align-left"></colgroup> 
| 

异常类

 | 

模块

 | 

描述

 |
| --- | --- | --- |
| `DatabaseError` | `mysql.connector``mysqlx` | 对于一般数据库错误。除了以 HY 开头的 SQL 状态之外，这个类不常被直接使用。 |
| `DataError` | `mysql.connector``mysqlx` | 与非约束错误的数据相关的错误。示例包括数据类型错误或不适合字段，或者提供了错误数量的值。 |
| `Error` | `mysql.connector``mysqlx` | 这是基本异常类。不直接使用。 |
| `IntegrityError` | `mysql.connector``mysqlx` | 约束错误或 XA 事务错误。 |
| `InterfaceError` | `mysql.connector``mysqlx` | 用于与连接相关的错误。 |
| `InternalError` | `mysql.connector``mysqlx` | 内部数据库错误，如死锁和未处理的结果。 |
| `NotSupportedError` | `mysql.connector``mysqlx` | 当使用尚未实现的功能时发生。这通常与在错误的上下文中使用特性有关，例如在存储函数中返回结果集。当 4.1.1 (MySQL Server 版本)之前的身份验证协议不可用时，也可以使用该协议进行连接。 |
| `OperationalError` | `mysql.connector``mysqlx` | 与数据库操作相关的错误。这是进行连接时最常遇到的情况。 |
| `PoolError` | `mysql.connector``mysqlx` | 有关连接池的错误。 |
| `ProgrammingError` | `mysql.connector``mysqlx` | 广义上与应用程序相关的错误。包括语法错误和试图访问不存在或用户无权访问的数据库对象。 |
| `Warning` | `mysql.connector` | 用于重要警告。 |

下面的类都是`DatabaseError`类的子类:`InternalError`、`OperationalError`、`ProgrammingError`、`IntegrityError`、`DataError`和`NotSupportedError`。

所有类的特征都是在基类`Error`中定义的，所以它们对于除了`Warning`类之外的所有异常类都是一样的。除了所有异常所具有的特性之外，`Warning`类没有什么特别的特性。为了帮助讨论错误异常的特征，考虑以下未捕获的异常:

```py
mysql.connector.errors.ProgrammingError: 1046 (3D000): No database selected

```

错误类有三个公共属性，可以在处理异常时使用:

*   **msg** :这是描述错误的字符串。在本例中，它是“没有选择数据库”

*   errno:MySQL 错误号。在示例中，它是 1046。

*   **SQL state**:SQL 状态。在示例中，它是 3D000。

清单 [9-6](#Par111) 显示了一个触发与刚才讨论的异常相同的异常的例子。异常被捕获，每个属性都被打印出来。最后，将错误号与来自`errorcode`子模块的常数进行比较。

```py
import mysql.connector
from mysql.connector import errors
from mysql.connector.errorcode import *

db = mysql.connector.connect(
  option_files="my.ini")

cursor = db.cursor()
try:
  cursor.execute("SELECT * FROM city")

except errors.ProgrammingError as e:

  print("Msg .........: {0}"
    .format(e.msg))
  print("Errno .......: {0}"
    .format(e.errno))
  print("SQL State ...: {0}"
    .format(e.sqlstate))
  print("")
  if e.errno == ER_NO_DB_ERROR:
    print("Errno is ER_NO_DB_ERROR")

db.close()

Listing 9-6Example of Handling an Exception

```

在 Python 中，异常像往常一样被捕获，属性的用法很简单。正如您之前看到的，错误号可以与`errorcode`子模块中的常数进行比较，以便更容易地看到异常与哪个错误进行比较。该示例的输出是

```py
Msg .........: No database selected
Errno .......: 1046
SQL State ...: 3D000

Errno is ER_NO_DB_ERROR

```

MySQL 连接器/Python 如何决定应该使用哪个类？这在上一节讨论 SQL 状态时已经部分回答了，但是让我们更详细地看一下这个主题。

### 将错误映射到异常类

当错误发生时，MySQL Connector/Python 使用错误号和 SQL 状态来确定使用哪个异常类。在大多数情况下，您不需要担心这一点，但是在某些情况下，您可能需要修改所使用的类(目前只有`mysql.connector`模块支持这一点)，并且在所有情况下，理解底层过程都是有用的。

使用以下步骤确定异常类别:

1.  如果已经为 MySQL 错误号定义了一个自定义异常，就使用它。自定义异常仅适用于`mysql.connector`模块，将在这些步骤后讨论。

2.  如果 MySQL 错误号是在`errors._ERROR_EXCEPTIONS`列表中定义的，那么使用为该错误定义的类。

3.  如果没有为错误定义 SQL 状态，则使用`DatabaseError`类。对于作为错误引发的警告，会发生这种情况。

4.  根据 SQL 状态在`errors._SQLSTATE_CLASS_EXCEPTION`列表中找到类。

5.  使用`DatabaseError`类。

如果您需要一个错误来触发不同的异常，当然可以修改`_ERROR_EXCEPTIONS`和`_SQLSTATE_CLASS_EXCEPTION`列表。但是，不建议这样做，因为它们应该是私有的(因此名称开头有下划线)。在`mysql.connector`模块中，有一种更好的方法:自定义异常。

### 自定义例外

在某些情况下，使用自定义异常来处理特定错误会很有用。当错误发生时，您可能希望触发一个特殊的工作流，例如将一条消息记录到应用程序日志中。目前只有`mysql.connector`模块支持自定义异常。

使用`errors.` `custom_error_exception()`功能登记自定义异常。您需要提供将使用异常的 MySQL 错误号和异常本身。建议自定义异常类继承`error` `.Error`类来包含基本特性。

清单 [9-7](#Par125) 显示了一个例子，其中`MyError`类被用于`ER_NO_DB_ERROR`错误。与普通类相比，唯一的区别是它向`stderr`输出一条包含错误信息的消息。如果你使用的是 Python 2.7，你需要添加`"from __future__ import print_function"`作为代码的第一行。

```py
import mysql.connector
from mysql.connector import errors
from mysql.connector.errorcode \
  import ER_NO_DB_ERROR

# Define the custom exception class

class MyError(errors.Error):

  def __init__(
    self, msg=None, errno=None,
    values=None, sqlstate=None):

    import sys
    super(MyError, self).__init__(
      msg, errno, values, sqlstate)
    print("MyError: {0} ({1}): {2}"
      .format(self.errno,
              self.sqlstate,
              self.msg
      ), file=sys.stderr)

# Register the class

errors.custom_error_exception(

  ER_NO_DB_ERROR,
  MyError

)

# Now cause the exception to be raised
db = mysql.connector.connect(
  option_files="my.ini")

cursor = db.cursor()
try:
  cursor.execute("SELECT * FROM city")

except MyError as e:

  print("Msg .........: {0}"
    .format(e.msg))
  print("Errno .......: {0}"
    .format(e.errno))
  print("SQL State ...: {0}"
    .format(e.sqlstate))

db.close()

Listing 9-7Using a Custom Exception

```

首先，定义了`MyError`类。它调用自己的超类的`__init__`方法来设置所有的标准属性。然后错误信息被打印到`stderr`。这也可以使用日志服务或其他逻辑。其次，`MyError`类被注册为错误的异常类，MySQL 错误号被设置为`ER_NO_DB_ERROR`。

程序的其余部分与之前相同，只是您现在捕获的是`MyError`异常，而不是`ProgrammingError`异常。执行程序时的输出是

```py
MyError: 1046 (3D000): No database selected
Msg .........: No database selected
Errno .......: 1046
SQL State ...: 3D000

```

这里假设`stderr`和`stdout`都被打印到控制台。作为练习，先将`stderr`重定向，然后将`stdout`重定向到其他地方，看看这会如何改变输出。

还有一些问题不一定会返回警告或错误。一组可能返回错误也可能不返回错误的问题是锁定问题。因为锁定问题是关于使用数据库的，所以您应该检查它们。

## 锁定问题

当两个或多个事务(可以是单个查询)试图以不兼容的方式访问或更新相同的数据时，就会发生锁定问题。数据库中的锁这个主题既庞大又复杂，但也很有趣。关于锁定的细节已经超出了本书的范围，但是本节将提供一个简要的概述。

### 注意

简化了锁的讨论；例如，只提到了行(记录)锁。其他一些锁是间隙锁、表锁、元数据锁和全局读锁。还有不同的锁类型，如意向锁。事务隔离级别也对锁起作用。*MySQL 参考手册*有好几页是关于 InnoDB 锁的。起点是 [`https://dev.mysql.com/doc/refman/en/innodb-locking-transaction-model.html`](https://dev.mysql.com/doc/refman/en/innodb-locking-transaction-model.html) 。

锁定的原因是允许对数据的并发访问，同时仍然确保一致的结果。如果一个事务更新给定的行，然后另一个事务尝试更新同一行，则第二个事务必须等待第一个事务完成(提交或回滚)才能访问该行。如果不是这样，最终结果将是不确定的。

MySQL 中的两个事务存储引擎 InnoDB 和 NDBCluster 都使用行级锁。这意味着只有查询读取或更改的行被锁定。因为直到访问行时才知道是否需要它，所以查询乐观地执行，假设有可能获得所需的锁。

乐观方法在大多数情况下都很有效，但这也意味着有时查询必须等待锁。甚至可能是因为等待时间太长而导致超时。

另一种可能性是，当两个事务都在等待对方的锁时，就会发生冲突。这种情况永远不会自行解决，被称为死锁。死锁这个名字听起来很吓人，但它只是一种情况的名称，在这种情况下，数据库必须进行干预以解决锁问题。InnoDB 选择完成工作最少的事务并回滚它。在这种情况下会返回一个死锁错误，这样应用程序就知道了事务失败的原因。清单 [9-8](#Par138) 显示了一个简单的例子，其中两个连接以死锁结束。

```py
Connection 1> START TRANSACTION;
Query OK, 0 rows affected (0.00 sec)

Connection 1> UPDATE world.city
                 SET Population = Population + 100
               WHERE Name = 'San Francisco' AND CountryCode = 'USA';
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

Connection 2> START TRANSACTION;
Query OK, 0 rows affected (0.00 sec)

Connection 2> UPDATE world.city
                 SET Population = Population + 200
               WHERE Name = 'Sydney' AND CountryCode = 'AUS';
Query OK, 1 row affected (0.04 sec)
Rows matched: 1  Changed: 1  Warnings: 0

Connection 1> UPDATE world.city
                 SET Population = Population + 100
               WHERE Name = 'Sydney' AND CountryCode = 'AUS';
-- Connection 1 blocks until the deadlock occurs for Connection 2.

Connection 2> UPDATE world.city
                 SET Population = Population + 200
               WHERE Name = 'San Francisco' AND CountryCode = 'USA';

ERROR 1213 (40001): Deadlock found when trying to get lock; try restarting

transaction

Listing 9-8Example of Two Transactions Causing a Deadlock

```

这两项交易都试图增加悉尼和旧金山的人口；连接 1 有 100 人的那个，连接 2 有 200 人的那个。但是，它们以相反的顺序更新这两个城市，并且是交错的。因此，最后，连接 1 等待悉尼的锁被释放，连接 2 等待旧金山的锁被释放。这是永远不会发生的，所以这是一个僵局。

使用细粒度锁时，锁等待和死锁是不可避免的。记住这一点并确保您的应用程序能够处理锁问题是很重要的。如果锁等待超时或死锁很少发生，重试事务通常就足够了。如果问题发生得如此频繁，以至于影响到性能，那么您需要努力减少锁争用。下一章将简要讨论锁的故障排除。

### 小费

确保您的应用程序能够处理锁等待和死锁。第一种方法是重试事务，可能会有一点延迟，以便给另一个事务一个完成的机会。应该进一步调查频繁出现的锁定问题。

最后要讨论的是当出现警告、错误或其他问题时该怎么办。

## 出问题时该怎么办

到目前为止，关于警告和错误的讨论一直集中在警告和错误如何与 MySQL Connector/Python 一起工作。然而，一个相当重要的问题仍然存在:当您遇到警告、错误和其他问题时，您会怎么做？

这个问题的简短答案是“视情况而定”不仅要看问题，还要看情况。以下是一些需要考虑的事项:

*   **严重性**:问题有多严重？

*   **影响**:问题影响了多少人和谁？

*   **频率**:问题出现的频率？

*   **可重试**:是否值得重试导致错误的操作？

*   **努力**:要避免这个问题需要做多少工作？

另一个考虑是如何报告失败。如果它涉及到生产环境，相对简短的消息是最好的。如果可能，提供如何避免问题和/或如何获得帮助的信息。

包含完整的堆栈跟踪和确切的异常似乎是个好主意；但是，最终用户无法使用这些信息。事实上，在某些情况下，向前端返回如此多的细节看起来是不专业的，甚至可能会泄露终端用户不应该知道的应用程序的细节。

错误的全部细节，包括跟踪，当然是开发人员非常感兴趣的。具体如何记录取决于应用程序，但是可以将其写入应用程序日志或单独的错误日志。开发环境中的另一个选项是支持“调试”模式，该模式将完整的细节输出到前端，以便在测试期间更容易获得信息。

最后，您希望如何呈现错误取决于您的特定需求、目标用户等等。在某些情况下，甚至有可能避免最终用户受到所遇到问题的影响。这使我们回到了本节开头列出的五个项目；它们将在下面的小节中讨论。

### 严重

问题的严重性在于它对应用程序的其余部分和用户有多重要。如果一个错误导致应用程序根本无法工作，那么处理这个错误显然比导致响应稍慢的错误更重要。

严重程度高的问题需要快速处理。如果是安全问题，或者网站不可用，延迟的解决方案会给公司造成损失。另一方面，如果一百万个请求中有一个比正常情况下多花了 5%的时间处理，这可能仍然是一件令人烦恼的事情，但并不值得你放弃正在做的一切。除了严重性之外，影响是决定问题紧迫性的另一个主要因素。

### 影响

无论是在面向客户的生产环境、内部非关键应用程序还是开发系统中遇到问题，都有很大的不同。受影响的用户数量越多，公司对应用程序的依赖程度越高，解决问题就越紧迫。

在给定的环境中，也可能存在差异。考虑一个开发环境。如果您是唯一受影响的人，并且该问题不影响您当前正在进行的工作，您可以推迟解决方案的工作。

然而，如果 100 个其他开发人员无所事事，或者他们的工作受到影响，那么解决这个问题就变得更加紧迫。问题出现的频率显然也会对影响产生影响。

### 频率

一个问题的频繁程度会影响需要付出多少努力。如果您很少遇到死锁或锁等待超时的情况，只需重试查询就可以了(参见下一条)。如果相同的锁定问题在一分钟内发生多次，就有必要研究如何避免该问题。

问题发生频率的限制取决于问题的性质，这将频率与严重性和影响联系起来。如果客户遇到应用程序崩溃，这很快就会成为必须立即处理的问题。同样，一个小时后失败的报告作业必须从头重新启动。

另一方面，如果同样一个小时的报告任务在每次出现问题时都被延迟了几秒钟，那么它就不太可能是优先任务。

### 可重试

您在 MySQL Connector/Python 中遇到的错误可以分为两类:一类是无论您尝试多少次都会失败的错误，另一类是如果您重试就可能成功的错误。后者更值得关注，因为您可以添加对自动处理它们的支持。

可重试错误通常是由锁争用或资源耗尽引起的。我已经讨论过锁，所以让我们从 MySQL 的角度来看一下是什么导致了资源耗尽。

在连接的生命周期中，有几个地方需要资源。当第一次创建连接时，MySQL 服务器中必须有更多可用的连接，并且操作系统必须允许创建新的线程(默认情况下，MySQL 为每个连接创建一个操作系统线程)。当执行一个查询时，它将需要内存来执行不同的部分，例如对结果进行排序。如果您插入或更改数据，也可能导致表格增长，这需要额外的磁盘空间。如果这些资源耗尽，查询将会失败。

如果您重试查询，并非所有这些错误都有可能消失。例如，如果磁盘已满，可能需要数据库管理员和/或系统管理员进行干预，然后才能再次插入数据。另一方面，如果您有一个锁定问题，并且您的事务都是短期的，那么重试失败的事务可能会成功。

表 [9-4](#Tab4) 显示了一些可以选择重试的典型错误号。

表 9-4

可能失效的 mysql 错误号

<colgroup><col class="tcol1 align-left"> <col class="tcol2 align-left"> <col class="tcol3 align-left"> <col class="tcol4 align-left"></colgroup> 
| 

错误号

 | 

常数

 | 

SQL 状态

 | 

描述

 |
| --- | --- | --- | --- |
| `1028` | `ER_FILSORT_ABORT` | `HY000` | 排序操作已中止。 |
| `1038` | `ER_OUT_OF_SORTMEMORY` | `HY001` | 由于内存不足，排序操作中止。可能需要增加 MySQL 会话变量`sort_buffer_size`。 |
| `1040` | `ER_CON_COUNT_ERROR` | `08004` | MySQL 连接器/Python 无法连接到 MySQL 服务器，因为所有分配的连接(`max_connections`)都已被使用。 |
| `1041` | `ER_OUT_OF_RESOURCES` | `HY000` | MySQL 服务器内存不足，但也许可以继续。 |
| `1043` | `ER_HANDSHAKE_ERROR` | `08S01` | 如果存在网络问题，在创建连接时会发生这种情况。 |
| `1114` | `ER_RECORD_FILE_FULL` | `HY000` | 桌子满了。 |
| `1135` | `ER_CANT_CREATE_THREAD` | `HY000` | 不可能为新连接创建线程。这可能是由于内存、文件描述符或允许的进程数耗尽。 |
| `1180` | `ER_ERROR_DURING_COMMIT` | `HY000` | 提交事务时出错。 |
| `1181` | `ER_ERROR_DURING_ROLLBACK` | `HY000` | 回滚事务时出错。 |
| `1203` | `ER_TOO_MANY_USER_CONNECTIONS` | `42000` | 用户有太多连接。 |
| `1205` | `ER_LOCK_WAIT_TIMEOUT` | `HY000` | 事务等待锁的时间超过了超时时间(InnoDB 默认为 50 秒)。 |
| `1206` | `ER_LOCK_TABLE_FULL` | `HY000` | 如果与 InnoDB 缓冲池的大小相比锁太多，InnoDB 就会发生这种情况。只有当不是事务本身导致大量锁时，才值得重试。 |
| `1213` | `ER_LOCK_DEADLOCK` | `40001` | 出现死锁，该事务被选作牺牲品。 |
| `1226` | `ER_USER_LIMIT_REACHED` | `42000` | 超过了用户资源限制。 |
| `1613` | `ER_XA_RBTIMEOUT` | `XA106` | XA 事务已回滚，因为花费的时间太长。 |
| `1614` | `ER_XA_RBDEADLOCK` | `XA102` | 由于死锁，XA 事务已回滚。 |
| `1615` | `ER_NEED_REPREPARE` | `HY000` | 准备好的语句需要重新准备。 |

错误列表并不是详尽无遗的，重试成功的机会各不相同。

请注意，您可能能够针对某些错误编写解决方案。例如，如果超过了`max_sp_recursion_depth`变量允许的递归深度，就会出现错误号 1456 ( `ER_SP_RECURSION_LIMIT`，SQL 状态 HY000)。如果您已将此选项设置为相对较低的值，但在某些情况下接受增加该值，则可以增加会话的值并重试。显然，对于这种特定情况，如果在第一次尝试之前增加该值会更好，但可能会有一些特殊的考虑因素阻止这样做。

如果决定重试一个事务，还需要决定重试最近的语句是否足够，或者是否必须重试整个事务。通常是后者，并且在所有情况下，它是最安全的。

### 警告

可能很想重试事务中的最后一条语句，但是要小心，因为前面的语句可能已经回滚了。

自动重试由于连接丢失而失败的查询是很诱人的。但是，在这种情况下要小心，要确保查询依赖的所有内容，比如同一事务中的早期查询，也会被重新执行。

### 努力

最后要注意的是解决问题的努力。在一个理想的世界里，所有的 bug 都会被修复，但是在现实中，资源是有限的，所以经常需要进行优先级排序。这个想法把所有先前的考虑联系在一起。

软件项目越大，确定哪些问题应该按照什么顺序修复就变得越复杂。可能存在一些利益冲突，例如两个客户受到不同问题的影响。可能还需要新功能的开发保持在正轨上。在这种情况下，有必要让多方参与讨论，以确定所需工作的优先顺序。

MySQL Connector/Python 中警告和错误处理的讨论到此结束。一个相关的主题是如何解决你遇到的错误，这将在下一章讨论。

## 摘要

本章探讨了警告和错误在 MySQL Server 和 MySQL Connector/Python 中是如何工作的。警告和错误有三种严重级别:注释、警告和错误。

您首先看到了如何使用 MySQL Server 中的`sql_notes`选项来改变注释级消息是否被视为警告。还可以配置 MySQL 服务器是否应该在严格模式下运行。最后，您看到了应该监视 MySQL 错误日志，以检查应用程序是否记录了任何消息。

在 MySQL Connector/Python 中，您应该检查警告，并验证它们是否是更严重问题的迹象。至少在开发过程中，让 MySQL Connector/Python 抛出警告作为异常是有用的；然而，这仅在对`mysql.connector`模块使用游标时才可用，并且仍然需要您获取警告。

错误消息由错误号、SQL 状态和文本消息组成。在`mysql.connector`和`mysqlx`的`errorcode`子模块中，错误号也是常量。当您回到代码的这一部分，并且不再记得例如错误号 1046 的含义时，使用常量可以更容易地理解正在使用的错误。

SQL 状态可用于确定错误的总体类别。它们还与错误号一起用于决定使用哪个异常类。非 MySQL 错误通常使用一个标准的 Python 异常类，而 MySQL 错误使用几个特定于 MySQL Connector/Python 的类中的一个。当您使用`mysql.connector`模块时，也可以为给定的 MySQL 错误号注册您自己的定制异常类。

本章的最后一部分研究了什么是锁定问题，以及遇到问题时应该怎么做。最后，错误可能需要排除，这是下一章的主题。